---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - microseg.xinyan.cn
  resources:
  - microsegnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microseg.xinyan.cn
  resources:
  - microsegnetworkpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - microseg.xinyan.cn
  resources:
  - microsegnetworkpolicies/status
  verbs:
  - get
  - patch
  - update
